leftnav:
- identifier: 2e139d12-71d2-1d5c-aeea-b5f296fc40d9
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-12f5401f49a84ca1b9363a7d5d767267
  name: Quantum Information Science II, Part 1
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.371.1x+2T2018/about
  weight: 1000
- identifier: external-4381d35b5b264c14b5d6b111bd63dd08
  name: Quantum Information Science II, Part 2
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.371.2x+1T2018/about
  weight: 1010
- identifier: external-97187d6092e4437696c64704adc69e9a
  name: Quantum Information Science II, Part 3
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.371.3x+1T2018/about
  weight: 1020
